import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#faf9f6',
        'outline-variant': '#c0c9be',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#3c6f4c',
        error: '#ba1a1a',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f4f3f1',
        'on-secondary-fixed': '#00210e',
        'inverse-primary': '#92d6a1',
        'surface-container-high': '#e9e8e5',
        'error-container': '#ffdad6',
        'tertiary-container': '#4c6454',
        'surface-container-highest': '#e3e2e0',
        'on-tertiary-fixed': '#082013',
        primary: '#0b522a',
        tertiary: '#354c3d',
        'on-primary-fixed': '#00210d',
        'inverse-surface': '#2f312f',
        'on-primary-container': '#a5e9b3',
        'primary-fixed': '#aef2bc',
        background: '#faf9f6',
        'surface-dim': '#dbdad7',
        'surface-tint': '#296a40',
        'secondary-fixed-dim': '#9dd3aa',
        'inverse-on-surface': '#f2f1ee',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#c4dfcb',
        'on-secondary-fixed-variant': '#1d5031',
        'secondary-container': '#b8f0c4',
        'surface-bright': '#faf9f6',
        'secondary-fixed': '#b8f0c4',
        'on-background': '#1a1c1a',
        outline: '#707970',
        'on-surface-variant': '#404941',
        'tertiary-fixed-dim': '#b2cdb9',
        'surface-container': '#efeeeb',
        'on-error-container': '#93000a',
        'surface-variant': '#e3e2e0',
        'primary-fixed-dim': '#92d6a1',
        'primary-container': '#2a6b40',
        'on-tertiary-fixed-variant': '#344c3d',
        'on-primary': '#ffffff',
        'on-surface': '#1a1c1a',
        'tertiary-fixed': '#cee9d4',
        secondary: '#366947',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#0a522a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-padding': '120px',
        gutter: '32px',
        'stack-sm': '16px',
        'container-max': '1280px',
        'stack-md': '32px',
        'stack-lg': '64px',
        unit: '8px',
      },
      fontFamily: {
        'label-caps': ['var(--font-public-sans)', 'sans-serif'],
        'body-md': ['var(--font-public-sans)', 'sans-serif'],
        'body-lg': ['var(--font-public-sans)', 'sans-serif'],
        'headline-md': ['var(--font-work-sans)', 'sans-serif'],
        'headline-lg': ['var(--font-work-sans)', 'sans-serif'],
        'headline-xl': ['var(--font-work-sans)', 'sans-serif'],
      },
      fontSize: {
        'label-caps': [
          '14px',
          { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '300' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': [
          '48px',
          { lineHeight: '1.1', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'headline-xl': [
          '80px',
          { lineHeight: '1.0', letterSpacing: '-0.02em', fontWeight: '900' },
        ],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
